### ISSUE TITLE
avoid: Adjust vmlinuz and initrd.img

### ISSUE THREAD

**Issue by smartornot** [ros-realtime/linux-real-time-kernel-builder#11]
Just in case, if it can be of use to someone, in order to avoid the manual step "adjust vmlinuz and initrd.img" I used the build command: 
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LOCALVERSION=-raspi KDEB_PKGVERSION=5.4.99 -j `nproc`  deb-pkg

After that the initial command "sudo dpkg -i *.deb" do automatically the complete  installation.

Thanks to share, thanks for your work,
BR

**Comment by razr** [comment]
thanks @smartornot , this is helpful

**Comment by flynneva** [comment]
@razr want me to make a PR to update the `README` with this advice? it should save some time I think for everyone

**Comment by razr** [comment]
@flynneva I'm not sure we want to set ```KDEB_PKGVERSION``` to ```5.4.99```. We need to find a proper combination. it should be probably ```linux-raspi_5.4.0-1042-rt61``` in the end

**Comment by shuhaowu** [comment]
I just tried this via the command:

```
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KDEB_PKGVERSION=5.4.0-1047 LOCALVERSION=-raspi -j `nproc` deb-pkg
```

and the resulting package didn't seem to have updated the vmlinuz links correctly:

```
ubuntu@ubuntu:/boot$ ls -la
total 84880
drwxr-xr-x  4 root root     4096 Dec 27 05:51 .
drwxr-xr-x 20 root root     4096 Dec 27 05:39 ..
-rw-------  1 root root  4167480 Jul 29 16:30 System.map-5.4.0-1042-raspi
-rw-r--r--  1 root root  4520617 Dec 27 04:03 System.map-5.4.151-rt65-raspi
-rw-r--r--  1 root root   219341 Jul 29 16:30 config-5.4.0-1042-raspi
-rw-r--r--  1 root root   218401 Dec 27 04:03 config-5.4.151-rt65-raspi
lrwxrwxrwx  1 root root       45 Dec 27 05:51 dtb -> dtbs/5.4.151-rt65-raspi/./bcm2711-rpi-4-b.dtb
lrwxrwxrwx  1 root root       43 Dec 27 05:44 dtb-5.4.0-1042-raspi -> dtbs/5.4.0-1042-raspi/./bcm2711-rpi-4-b.dtb
lrwxrwxrwx  1 root root       45 Dec 27 05:51 dtb-5.4.151-rt65-raspi -> dtbs/5.4.151-rt65-raspi/./bcm2711-rpi-4-b.dtb
drwxr-xr-x  4 root root     4096 Dec 27 05:51 dtbs
drwxr-xr-x  3 root root     4096 Dec 27 05:51 firmware
lrwxrwxrwx  1 root root       27 Aug 19 10:37 initrd.img -> initrd.img-5.4.0-1042-raspi
-rw-r--r--  1 root root 30347735 Dec 27 05:44 initrd.img-5.4.0-1042-raspi
-rw-r--r--  1 root root 30196294 Dec 27 05:51 initrd.img-5.4.151-rt65-raspi
lrwxrwxrwx  1 root root       27 Aug 19 10:37 initrd.img.old -> initrd.img-5.4.0-1042-raspi
lrwxrwxrwx  1 root root       24 Aug 19 10:37 vmlinuz -> vmlinuz-5.4.0-1042-raspi
-rw-------  1 root root  8400065 Jul 29 16:30 vmlinuz-5.4.0-1042-raspi
-rw-r--r--  1 root root  8813753 Dec 27 04:03 vmlinuz-5.4.151-rt65-raspi
lrwxrwxrwx  1 root root       24 Aug 19 10:37 vmlinuz.old -> vmlinuz-5.4.0-1042-raspi

```

**Comment by shuhaowu** [comment]
Correction: it seems like the `/boot/firmware/vmlinuz` and `/boot/firmware/initrd.img` files are correctly copied with the command above. This is copied via the `flash-kernel` function (called from control/postinst -> /etc/kernel/postinst.d/zz-flash-kernel -> /usr/sbin/flash-kernel). 

The reason it works with the command above and not the current default build is due to how `flash-kernel` works. Looking at its source code (/usr/share/flash-kernel/functions), we can see the line

```
latest_version=$(linux-version list | include_only_flavors $kflavors | linux-version sort | tail -1)
```

The crucial part is `include_only_flavors $kflavors`. I believe kflavors is coming from `/usr/share/flash-kernel/db/all.db`, which says: `Kernel-Flavors: raspi` for the Raspberry Pi 4.

This means the currently released package's postinst script calls flash-kernel without a `-raspi` post fix, which causes flash-kernel to ignore this kernel and not copy it.

I'm going to try compiling with only `LOCALVERSION=-raspi` and omit `KDEB_PKGVERSION`. If that works well, I can create a PR against the github workflow. 

Still not quite sure how the `/boot/vmlinuz` links are generated, but I'm not sure if it matters that much.

**Comment by shuhaowu** [comment]
Looked a bit more today and I see that the `postinst` script generated via the `make` command is very different from the ones from the upstream package. In the RT package, it is:

```
#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postinst.d && run-parts --arg="5.4.151-rt65-raspi" --arg="/boot/vmlinuz-5.4.151-rt65-raspi" /etc/kernel/postinst.d
exit 0
```

In the upstream package it is:

```
#!/bin/sh
set -e

version=5.4.0-1047-raspi
image_path=/boot/vmlinuz-$version

#
# When we install linux-image we have to run kernel postinst.d support to
# generate the initramfs, create links etc.  Should it have an associated
# linux-image-extra package and we install that we also need to run kernel
# postinst.d, to regenerate the initramfs.  If we are installing both at the
# same time, we necessarily trigger kernel postinst.d twice. As this includes
# rebuilding the initramfs and reconfiguring the boot loader this is very time
# consuming.
#
# Similarly for removal when we remove the linux-image-extra package we need to
# run kernel postinst.d handling in order to pare down the initramfs to
# linux-image contents only.  When we remove the linux-image need to remove the
# now redundant initramfs.  If we are removing both at the same time, then
# we will rebuilt the initramfs and then immediatly remove it.
#
# Switches to using a trigger against the linux-image package for all
# postinst.d and postrm.d handling.  On installation postinst.d gets triggered
# twice once by linux-image and once by linux-image-extra.  As triggers are
# non-cumulative we will only run this processing once.  When removing both
# packages we will trigger postinst.d from linux-image-extra and then in
# linux-image postrm.d we effectivly ignore the pending trigger and simply run
# the postrm.d.  This prevents us from rebuilding the initramfs.
#
if [ "$1" = triggered ]; then
    trigger=/usr/lib/linux/triggers/$version
    if [ -f "$trigger" ]; then
	sh "$trigger"
	rm -f "$trigger"
    fi
    exit 0
fi

if [ "$1" != configure ]; then
    exit 0
fi

depmod $version

if [ -f /lib/modules/$version/.fresh-install ]; then
    change=install
else
    change=upgrade
fi
linux-update-symlinks $change $version $image_path
rm -f /lib/modules/$version/.fresh-install

if [ -d /etc/kernel/postinst.d ]; then
    mkdir -p /usr/lib/linux/triggers
    cat - >/usr/lib/linux/triggers/$version <<EOF
DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
      --arg=$image_path /etc/kernel/postinst.d
EOF
    dpkg-trigger --no-await linux-update-$version
fi

exit 0
```

How the symlink is generated is via the `linux-update-symlinks` command. I'm not sure why this is generated differently. I looked through Ubuntu's documentation for building the kernel and all of them recommands the final build command to be something like `fakeroot debian/rules binary` as opposed to via `make`. I tried this but it fails due to an "unclean tree", which I presume is due to the patches (and the lack of changelog entries?). For the moment, I don't have time to look further, but it does appear that even with out the symlinks in /boot, the packages will install the kernel correctly to /boot/firmware, which allows boot to occur.
